{
 "title": "OwnTracks",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tid",
    "label": "Device Identifier",
    "query": {
     "query": "label_values(owntracks_requests{type=\"location\"},tid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(owntracks_requests{tid=\"$tid\"}[$__rate_interval]) * $__interval",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "owntracks_battery_charge{tid=\"$tid\"}",
     "legendFormat": "charge"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "owntracks_location{tid=\"$tid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coordinates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "owntracks_location{tid=\"$tid\"}",
     "legendFormat": "{{coordinate}}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "owntracks_altitude{tid=\"$tid\"}",
     "legendFormat": "altitude"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "rate(owntracks_distance{tid=\"$tid\"}[$__rate_interval]) * 3600",
     "legendFormat": "speed"
    }
   ]
  },
  {
   "title": "Distance travelled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "targets": [
    {
     "expr": "rate(owntracks_distance{tid=\"$tid\"}[$__interval]) * $__interval",
     "legendFormat": "change"
    }
   ]
  }
 ]
}